### PR TITLE
update ui to match android

### PR DESCRIPTION
**Pull request by edewit**
@danielpassos @corinnekrych updated to look similar, but still window-y

### CODE REVIEW

**Comment by corinnekrych** [comment]
:eyes:

**Comment by corinnekrych** [comment]
+1
working fine

**Comment by corinnekrych** [comment]
@edewit could you clear saml-windows/saml-windows.Shared/fhconfig.json with `replaceme` placeholder?

**Comment by edewit** [comment]
@corinnekrych will they not be replaced automatically by the platform? I've changed them in master

**Comment by corinnekrych** [comment]
@edewit yeap agreed they will eventually be replaced, just to be clean it
+1 to merge

**Pull request merged**
